#!/usr/bin/env bash
#
# A wizard walks a human through a manual procedure, step by step.
# Generated by the /wizard skill.
#
# Everything above the "STAGES" marker is the wizard library: do not hand-edit
# it. Author the per-step stages below the marker.

set -euo pipefail

# ──────────────────────────────────────────────────────────────────────────
# Wizard library: delightful, consistent UX, identical across every wizard.
# ──────────────────────────────────────────────────────────────────────────

if [[ -t 1 ]] && command -v tput >/dev/null 2>&1 && [[ "$(tput colors 2>/dev/null || echo 0)" -ge 8 ]]; then
  BOLD=$(tput bold); DIM=$(tput dim); RESET=$(tput sgr0)
  BLUE=$(tput setaf 4); GREEN=$(tput setaf 2); YELLOW=$(tput setaf 3); RED=$(tput setaf 1)
else
  BOLD=""; DIM=""; RESET=""; BLUE=""; GREEN=""; YELLOW=""; RED=""
fi

# Author sets this at the top of the stages section.
TOTAL_STAGES=0

_STAGE_INDEX=0
ENV_FILE="${ENV_FILE:-.env}"
WRITTEN_ENV=()    # KEYs written to ENV_FILE this run
WRITTEN_SECRET=() # secret NAMEs set this run
SKIPPED=()        # things we couldn't do (e.g. gh missing)

# _clear wipes the terminal so only the current step is on screen. No-op when
# output isn't a terminal, so piped logs stay readable.
_clear() {
  [[ -t 1 ]] || return 0
  if command -v tput >/dev/null 2>&1; then tput clear; else printf '\033[2J\033[3J\033[H'; fi
}

# banner "Title" shows the opening frame: what this wizard does.
banner() {
  _clear
  printf '\n%s%s  %s%s\n' "$BOLD" "$BLUE" "$1" "$RESET"
  printf '%s  %s stages%s\n\n' "$DIM" "$TOTAL_STAGES" "$RESET"
  printf '%s  You drive the browser; this wizard tells you exactly what to do and\n' "$DIM"
  printf '  captures the values you copy back. Stop any time with Ctrl-C and re-run\n'
  printf '  later, since it remembers values already saved.%s\n' "$RESET"
  pause "Ready to start?"
}

# stage "Name" clears the screen, then announces a stage and shows progress.
# Clearing keeps only the current step on screen.
stage() {
  _clear
  _STAGE_INDEX=$((_STAGE_INDEX + 1))
  printf '\n%s%s▸ Stage %s/%s · %s%s\n' \
    "$BOLD" "$BLUE" "$_STAGE_INDEX" "$TOTAL_STAGES" "$1" "$RESET"
}

# say "..." prints a plain instruction line.
say()  { printf '  %s\n' "$1"; }
# step "..." is a numbered-feeling action the human takes in the browser.
step() { printf '  %s•%s %s\n' "$BLUE" "$RESET" "$1"; }
note() { printf '  %s%s%s\n' "$DIM" "$1" "$RESET"; }
warn() { printf '  %s⚠ %s%s\n' "$YELLOW" "$1" "$RESET"; }

# open_url URL opens it in the human's browser, cross-platform incl. WSL.
open_url() {
  local url="$1"
  printf '  %s↗ opening%s %s\n' "$GREEN" "$RESET" "$url"
  { if   command -v wslview     >/dev/null 2>&1; then wslview "$url"
    elif command -v explorer.exe >/dev/null 2>&1; then explorer.exe "$url"
    elif command -v xdg-open    >/dev/null 2>&1; then xdg-open "$url"
    elif command -v open        >/dev/null 2>&1; then open "$url"
    else warn "couldn't open a browser; visit it manually: $url"; fi
  } >/dev/null 2>&1 || warn "couldn't open a browser, so visit it manually: $url"
}

# pause "msg" waits for the human to confirm they've done the manual part.
pause() {
  printf '  %s%s%s ' "$DIM" "${1:-Press Enter to continue}" "$RESET"
  read -r _ || true
}

# confirm "question" is a y/N gate; returns success on yes.
confirm() {
  local reply=""
  printf '  %s? %s [y/N] ' "$YELLOW" "$1"
  read -r reply || true
  [[ "$reply" =~ ^[Yy] ]]
}

# _existing KEY: current value of KEY in ENV_FILE, if any.
_existing() {
  [[ -f "$ENV_FILE" ]] || return 1
  local line; line=$(grep -E "^${1}=" "$ENV_FILE" | tail -n1) || return 1
  printf '%s' "${line#*=}"
}

# ask KEY "Prompt" reads a value into $KEY. Offers the existing .env value as
# a default on re-runs (Enter keeps it). Visible input (non-secret).
ask() {
  local key="$1" prompt="$2" current input
  current=$(_existing "$key" || true)
  if [[ -n "$current" ]]; then
    printf '  %s%s%s %s[Enter keeps current]%s ' "$BOLD" "$prompt" "$RESET" "$DIM" "$RESET"
  else
    printf '  %s%s%s ' "$BOLD" "$prompt" "$RESET"
  fi
  read -r input || true
  [[ -z "$input" && -n "$current" ]] && input="$current"
  printf -v "$key" '%s' "$input"
}

# ask_secret KEY "Prompt" is like ask, but input is hidden.
ask_secret() {
  local key="$1" prompt="$2" current input
  current=$(_existing "$key" || true)
  if [[ -n "$current" ]]; then
    printf '  %s%s%s %s[Enter keeps current]%s ' "$BOLD" "$prompt" "$RESET" "$DIM" "$RESET"
  else
    printf '  %s%s%s ' "$BOLD" "$prompt" "$RESET"
  fi
  read -rs input || true
  printf '\n'
  [[ -z "$input" && -n "$current" ]] && input="$current"
  printf -v "$key" '%s' "$input"
}

# write_env KEY VALUE upserts KEY=VALUE into ENV_FILE (creates it; replaces
# any existing line). Idempotent.
write_env() {
  local key="$1" value="$2" tmp
  touch "$ENV_FILE"
  tmp=$(mktemp)
  grep -vE "^${key}=" "$ENV_FILE" > "$tmp" || true
  printf '%s=%s\n' "$key" "$value" >> "$tmp"
  mv "$tmp" "$ENV_FILE"
  WRITTEN_ENV+=("$key")
  printf '  %s✓ wrote%s %s → %s\n' "$GREEN" "$RESET" "$key" "$ENV_FILE"
}

# set_secret NAME VALUE sets a GitHub Actions repo secret via gh. Falls back
# to a warning (and records it) if gh is unavailable or unauthenticated.
set_secret() {
  local name="$1" value="$2"
  if command -v gh >/dev/null 2>&1 && gh auth status >/dev/null 2>&1; then
    if printf '%s' "$value" | gh secret set "$name" >/dev/null 2>&1; then
      WRITTEN_SECRET+=("$name")
      printf '  %s✓ set%s GitHub secret %s\n' "$GREEN" "$RESET" "$name"
      return
    fi
  fi
  SKIPPED+=("GitHub secret $name (set it manually: gh secret set $name)")
  warn "skipped GitHub secret $name: gh not ready; set it later"
}

# set_var NAME VALUE sets a GitHub Actions repo variable (non-secret).
set_var() {
  local name="$1" value="$2"
  if command -v gh >/dev/null 2>&1 && gh auth status >/dev/null 2>&1; then
    if gh variable set "$name" --body "$value" >/dev/null 2>&1; then
      printf '  %s✓ set%s GitHub variable %s\n' "$GREEN" "$RESET" "$name"
      return
    fi
  fi
  SKIPPED+=("GitHub variable $name")
  warn "skipped GitHub variable $name, gh not ready; set it later"
}

# finish clears, then shows a closing summary of everything configured.
finish() {
  _clear
  printf '\n%s%s  ✓ Setup complete%s\n' "$BOLD" "$GREEN" "$RESET"
  (( ${#WRITTEN_ENV[@]} ))    && note "wrote ${#WRITTEN_ENV[@]} value(s) to $ENV_FILE: ${WRITTEN_ENV[*]}"
  (( ${#WRITTEN_SECRET[@]} )) && note "set ${#WRITTEN_SECRET[@]} GitHub secret(s): ${WRITTEN_SECRET[*]}"
  if (( ${#SKIPPED[@]} )); then
    printf '\n'; warn "still to do by hand:"
    for s in "${SKIPPED[@]}"; do note "  - $s"; done
  fi
  printf '\n'
}

# ──────────────────────────────────────────────────────────────────────────
# STAGES: author this section. One stage() per step the human takes.
# Replace the example below. Set TOTAL_STAGES to match the stages you write.
# ──────────────────────────────────────────────────────────────────────────

# One-time setup for public releases (docs/adr/0003-signed-releases-via-own-homebrew-tap.md).
# Only the human and the Account Holder of the paid team can do these steps.
# Re-running skips every stage that is already done.

TOTAL_STAGES=5

NOTARY_PROFILE=pacemark-notary
TAP_REPO=chris-metz/homebrew-tap

# identity: the first valid Developer ID Application identity, as the release
# script picks it, e.g. "Developer ID Application: Jane Doe (AB12CD34EF)".
identity()           { security find-identity -v -p codesigning | awk -F'"' '/"Developer ID Application: / { print $2; exit }'; }
has_identity()       { [[ -n "$(identity)" ]]; }
team_id()            { identity | sed -E 's/.*\(([A-Z0-9]+)\)$/\1/'; }
has_notary_profile() { xcrun notarytool history --keychain-profile "$NOTARY_PROFILE" >/dev/null 2>&1; }
has_tap()            { gh repo view "$TAP_REPO" >/dev/null 2>&1; }

# clean_path PATH: accepts a path typed or dragged in from Finder (quotes,
# escaped spaces, a leading ~, trailing whitespace).
clean_path() {
  local p="$1"
  p="${p%"${p##*[![:space:]]}"}"
  p="${p#\'}"; p="${p%\'}"; p="${p#\"}"; p="${p%\"}"
  p="${p//\\ / }"
  p="${p/#\~/$HOME}"
  printf '%s' "$p"
}

# ask_file VAR "Prompt" DEFAULT: asks until the path names an existing file.
ask_file() {
  local var="$1" prompt="$2" default="$3" input
  while true; do
    ask _FILE_INPUT "$prompt [Enter for $default]"
    input=$(clean_path "${_FILE_INPUT:-$default}")
    if [[ -f "$input" ]]; then printf -v "$var" '%s' "$input"; return; fi
    warn "No file at $input"
  done
}

banner "Pacemark release setup"

# ── 1: consent ─────────────────────────────────────────────────────────────
stage "Consent of the Account Holder"
say "Every release is signed with the Developer ID of the paid team, so it shows"
say "the Account Holder's full name and Team ID. Anyone can read both from the"
say "app, e.g. with codesign -dvv. Address, phone and email are not in it."
if ! confirm "Has the Account Holder agreed to their name appearing in every release?"; then
  warn "Stopping here. Ask the Account Holder first, then run this wizard again."
  exit 1
fi

# ── 2: certificate signing request ─────────────────────────────────────────
stage "Certificate signing request"
CSR=""
if has_identity; then
  say "Already in your keychain: $(identity). Nothing to do."
  pause
else
  say "Keychain Access creates a private key on this Mac plus a request for Apple."
  say "The key stays in your login keychain; only the request leaves this Mac."
  open "/System/Library/CoreServices/Applications/Keychain Access.app"
  step "Menu: Keychain Access → Certificate Assistant → Request a Certificate From a Certificate Authority…"
  step "User Email Address: your email. Common Name: Pacemark Developer ID. CA Email Address: leave empty."
  step "Choose 'Saved to disk', click Continue, and save it to the Desktop."
  ask_file CSR "Path of the saved request" "$HOME/Desktop/CertificateSigningRequest.certSigningRequest"
  printf '  %s✓ request ready%s %s\n' "$GREEN" "$RESET" "$CSR"
  pause
fi

# ── 3: Developer ID certificate ────────────────────────────────────────────
stage "Developer ID certificate (Account Holder)"
if has_identity; then
  say "Already in your keychain: $(identity). Nothing to do."
  pause
else
  say "The Account Holder does this part, signed in with their Apple ID."
  [[ -n "$CSR" ]] && say "If they aren't at this Mac, send them the request: $CSR"
  open_url "https://developer.apple.com/account/resources/certificates/add"
  step "Under Software, select Developer ID, then click Continue."
  step "Select Developer ID Application (if asked for a Sub-CA: G2), then Continue."
  step "Click Choose File, pick the request file, then Continue."
  step "Click Download and bring the .cer file to this Mac."
  ask_file CER "Path of the downloaded .cer" "$HOME/Downloads/developerID_application.cer"
  security import "$CER" -k "$HOME/Library/Keychains/login.keychain-db" || true
  if has_identity; then
    printf '  %s✓ in your keychain:%s %s\n' "$GREEN" "$RESET" "$(identity)"
  else
    warn "The keychain lists no valid Developer ID Application identity."
    note "Check that the request came from this Mac and that Apple's Developer ID G2"
    note "intermediate is installed: https://www.apple.com/certificateauthority/"
    exit 1
  fi
  pause
fi

# ── 4: notarization access ─────────────────────────────────────────────────
stage "Notarization access (Account Holder)"
if has_notary_profile; then
  say "The notarytool profile $NOTARY_PROFILE already works. Nothing to do."
  pause
else
  say "Apple's notary service needs a login. Best is a Team API key: it can only"
  say "do App Store Connect work, and the Account Holder can revoke it at any time."
  open_url "https://appstoreconnect.apple.com/access/integrations/api"
  step "The Account Holder signs in. If the page doesn't open there: Users and Access → Integrations."
  step "If 'Request Access' shows, request it first. Apple reviews that, so it can take a while."
  step "Team Keys → Generate API Key (or +). Name: Pacemark notarization. Access: Developer. Generate."
  step "Download the .p8 key. Apple offers this download only once."
  step "Note the Key ID (in the key's row) and the Issuer ID (above the table)."
  if confirm "Did you get a Team API key?"; then
    ask_file KEY "Path of the .p8 file" "$HOME/Downloads/AuthKey.p8"
    ask KEY_ID "Key ID:"
    ask ISSUER_ID "Issuer ID:"
    xcrun notarytool store-credentials "$NOTARY_PROFILE" \
      --key "$KEY" --key-id "$KEY_ID" --issuer "$ISSUER_ID" || true
    if has_notary_profile; then
      note "The key now lives in your keychain. Keep the .p8 in a password manager as a"
      note "backup, or move it to the Trash: the Account Holder can always generate a new one."
    fi
  else
    warn "The fallback is an app-specific password for the Account Holder's Apple ID."
    warn "It also lets third-party apps read their iCloud mail, contacts and calendars."
    if confirm "Use an app-specific password anyway?"; then
      open_url "https://account.apple.com"
      step "The Account Holder signs in → Sign-In and Security → App-Specific Passwords."
      step "Generate one named Pacemark notarization and copy it."
      ask APPLE_ID "The Account Holder's Apple ID (email):"
      say "notarytool asks for the app-specific password next; the input is hidden."
      xcrun notarytool store-credentials "$NOTARY_PROFILE" \
        --apple-id "$APPLE_ID" --team-id "$(team_id)" || true
    fi
  fi
  if has_notary_profile; then
    printf '  %s✓ notarytool profile ready:%s %s\n' "$GREEN" "$RESET" "$NOTARY_PROFILE"
  else
    SKIPPED+=("notarization access: re-run this wizard once there is a Team API key")
    warn "No working notarytool profile yet."
  fi
  pause
fi

# ── 5: tap repo ────────────────────────────────────────────────────────────
stage "Homebrew tap repo"
if has_tap; then
  say "github.com/$TAP_REPO already exists. Nothing to do."
  pause
elif ! gh auth status >/dev/null 2>&1; then
  SKIPPED+=("tap repo: run 'gh auth login', then re-run this wizard")
  warn "gh isn't logged in, so the tap repo can't be created now."
  pause
else
  say "Homebrew installs casks only from a tap: a repo named homebrew-<name>."
  say "This creates the public repo github.com/$TAP_REPO with just a README."
  say "The release script adds the cask to it."
  if confirm "Create github.com/$TAP_REPO now?"; then
    gh repo create "$TAP_REPO" --public --add-readme \
      --description "Homebrew tap for Pacemark"
  else
    SKIPPED+=("tap repo: re-run this wizard to create github.com/$TAP_REPO")
  fi
  pause
fi

finish
